apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: secret-mysql
  namespace: database
spec:
  encryptedData:
    password: AgAYkzhhI+3ZJ0PKyKYhWv8wU3oHgFf4UpIQ1jhjBoliHT41WD/bkXPU7/+iGMlsKPXnnDsRhTqrx2y0mlyfNnsOPga1OPXJi41qtp8pnva7BwFlgQZSKWTDDIkuJkcykVpEPiRFN7vmqPHQd9G5VJIGW5iRG/jX+n767W//bNPB+ycEAGNkJfqt9RxLBBMGIEmBoHIDis7OI1eMTsll/zhX43YmZLM+NFLJrzxyjUwuyiwsnIGmUtab3kkW5JhpxLIQR24W+M+mlvPrQM1iVEubroBSHAKZazXUnBjt5N95l2GqvJkOmqL0qwjWrhmPcUhIWCodrO5HUH/IEySrqMLDjVnd5c9xqqJvYOpClXWclmet0VsnPmq7InnvVxXys4gDRbLZMnMVoN4oPcBA8YXs5SeIfd8X8t6t3RIYe9jxKb0XH8H+V/TxmCWLOTvn91H61CtlWR/w6Q/k5COoHGODkY7G4/MKxG66/zifw3HWwT9HIeSdceC2xQBoXpDkIjK7vCQmLxbUKyNVZfJLo+2CesjCNjlmyw+jTjD4YlC8nT5yohjfLEvkBDnn/nLKnWGf9LAaLyhL/XdZj7vTVoT0fPB1LTmY4aqSXr+Im4R0AuueIYoblCc2x+kLiuD2XAm2k50f1f2WgffnMDWWU2B9F2HdX/IT6nDcurxaoyz9lUDgTWNv/0tWF81wH4w3WAtliTjtvC7ZglGxalFXQE18BnxQL3geic5V
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: secret-mysql
      namespace: database

